ALTER TABLE PUBLIC.ROUTE_ENTITY
ADD COLUMN PATHS JSON,
ADD COLUMN SETTINGS JSON;

UPDATE PUBLIC.ROUTE_ENTITY
SET SETTINGS = '{"alwaysAllowHEAD": true, "alwaysAllowOPTIONS": true}'
WHERE SETTINGS IS NULL;