CREATE TABLE IF NOT EXISTS PUBLIC.ROUTE_ENTITY (
	ID BIGINT AUTO_INCREMENT NOT NULL,
	ENDPOINT CHARACTER VARYING(255) NOT NULL,
	NAME CHARACTER VARYING(255) NOT NULL,
	VERSION CHARACTER VARYING(255) NOT NULL,
	SPECIFICATION CHARACTER LARGE OBJECT,
	ACTIVE BOOLEAN NOT NULL,
	FILTERS CHARACTER LARGE OBJECT,
	GLOBAL_FILTERS CHARACTER LARGE OBJECT,
	PATHS CHARACTER LARGE OBJECT,
	SETTINGS CHARACTER LARGE OBJECT,
	CONSTRAINT CONSTRAINT_4 PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC.OPEN_ID_CONNECT_ISSUER (
	ID BIGINT AUTO_INCREMENT NOT NULL,
	ISSUER CHARACTER VARYING(255) UNIQUE NOT NULL,
	TOKEN_INTROSPECTION_ENDPOINT CHARACTER VARYING(255),
	MATCH_MODE CHARACTER VARYING(20) NOT NULL,
	CLIENT_ID CHARACTER VARYING(255),
	CLIENT_SECRET CHARACTER VARYING(255),
	CONSTRAINT CONSTRAINT_5 PRIMARY KEY (ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC.GLOBAL_FILTER_ENTITY (
	NAME CHARACTER VARYING(255) UNIQUE NOT NULL,
	FILTER CHARACTER LARGE OBJECT NOT NULL,
	_VERSION INT,
	CONSTRAINT CONSTRAINT_8 PRIMARY KEY (NAME)
);